/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangunruangproject;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menultemKeluar = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menu2D = new javax.swing.JMenu();
        menultemPersegi = new javax.swing.JMenuItem();
        menultemPersegiPanjang = new javax.swing.JMenuItem();
        menultemLingkaran = new javax.swing.JMenuItem();
        menu3D = new javax.swing.JMenu();
        menuItemKubus = new javax.swing.JMenuItem();
        menultemBalok = new javax.swing.JMenuItem();
        menultemTabung = new javax.swing.JMenuItem();
        menultemBola = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Menghitung Bangun Ruang");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelHome.setLayout(new java.awt.BorderLayout());

        menuFile.setText("File");

        menultemKeluar.setText("Keluar");
        menultemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menultemKeluarActionPerformed(evt);
            }
        });
        menuFile.add(menultemKeluar);

        menuBar.add(menuFile);

        menuEdit.setText("Bangun Ruang");

        menu2D.setText("2 Dimensi");

        menultemPersegi.setText("Persegi");
        menultemPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menultemPersegiActionPerformed(evt);
            }
        });
        menu2D.add(menultemPersegi);

        menultemPersegiPanjang.setText("Persegi Panjang ");
        menultemPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menultemPersegiPanjangActionPerformed(evt);
            }
        });
        menu2D.add(menultemPersegiPanjang);

        menultemLingkaran.setText("Lingkaran");
        menultemLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menultemLingkaranActionPerformed(evt);
            }
        });
        menu2D.add(menultemLingkaran);

        menuEdit.add(menu2D);

        menu3D.setText("3 Dimensi");

        menuItemKubus.setText("Kubus");
        menuItemKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKubusActionPerformed(evt);
            }
        });
        menu3D.add(menuItemKubus);

        menultemBalok.setText("Balok");
        menultemBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menultemBalokActionPerformed(evt);
            }
        });
        menu3D.add(menultemBalok);

        menultemTabung.setText("Tabung");
        menultemTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menultemTabungActionPerformed(evt);
            }
        });
        menu3D.add(menultemTabung);

        menultemBola.setText("Bola");
        menultemBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menultemBolaActionPerformed(evt);
            }
        });
        menu3D.add(menultemBola);

        menuEdit.add(menu3D);

        menuBar.add(menuEdit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menultemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menultemKeluarActionPerformed
        // TODO add your handling code here:
        menuItemKeluarAction();
    }//GEN-LAST:event_menultemKeluarActionPerformed

    private void menultemPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menultemPersegiActionPerformed
        // TODO add your handling code here:
        menuItemPersegiAction();
    }//GEN-LAST:event_menultemPersegiActionPerformed

    private void menultemLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menultemLingkaranActionPerformed
        // TODO add your handling code here:
        menuItemLingkaranAction();
    }//GEN-LAST:event_menultemLingkaranActionPerformed

    private void menuItemKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKubusActionPerformed
        // TODO add your handling code here:
        menuItemKubusAction();
    }//GEN-LAST:event_menuItemKubusActionPerformed

    private void menultemBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menultemBalokActionPerformed
        // TODO add your handling code here:
        menuItemBalokAction();
    }//GEN-LAST:event_menultemBalokActionPerformed

    private void menultemBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menultemBolaActionPerformed
        // TODO add your handling code here:
        menuItemBolaAction();
    }//GEN-LAST:event_menultemBolaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setMaximumFrame();
    }//GEN-LAST:event_formWindowOpened

    private void menultemTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menultemTabungActionPerformed
        // TODO add your handling code here:
        menuItemTabungAction();
    }//GEN-LAST:event_menultemTabungActionPerformed

    private void menultemPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menultemPersegiPanjangActionPerformed
        // TODO add your handling code here:
        menuItemPersegiPanjangAction();
    }//GEN-LAST:event_menultemPersegiPanjangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menu2D;
    private javax.swing.JMenu menu3D;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemKubus;
    private javax.swing.JMenuItem menultemBalok;
    private javax.swing.JMenuItem menultemBola;
    private javax.swing.JMenuItem menultemKeluar;
    private javax.swing.JMenuItem menultemLingkaran;
    private javax.swing.JMenuItem menultemPersegi;
    private javax.swing.JMenuItem menultemPersegiPanjang;
    private javax.swing.JMenuItem menultemTabung;
    private javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables

private void setMaximumFrame() {
    try {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    } catch (Exception e) {
        System.out.println("Error maximizing frame: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Error maximizing frame: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void menuItemLingkaranAction() {
    try {
        LingkaranView lv = new LingkaranView();
        panelHome.add(lv);
        lv.setVisible(true);
    } catch (Exception error) {
        System.err.println("Error at HomeView-menuItemLingkaranAction, details: " + error.toString());
        JOptionPane.showMessageDialog(this, "Error: " + error.getMessage());
    }
}


private void menuItemBolaAction() {
    try {
        BolaView bv = new BolaView();
        panelHome.add(bv);
        bv.setVisible(true);
    } catch (Exception error) {
        System.err.println("Error at HomeView-menuItemBolaAction, details: " + error.toString());
        JOptionPane.showMessageDialog(this, "Error at HomeView-menuItemBolaAction, details: " + error.toString());
    }
}

private void menuItemPersegiPanjangAction() {
    try {
        PersegiPanjangView ppv = new PersegiPanjangView();
        panelHome.add(ppv);
        ppv.setVisible(true);
    } catch (Exception error) {
        System.err.println("Error at HomeView-menuItemPersegiPanjangAction, details: " + error.toString());
        JOptionPane.showMessageDialog(this, "Error at HomeView-menuItemPersegiPanjangAction, details: " + error.toString());
    }
}

private void menuItemKeluarAction() {
    try {
        System.exit(0);
    } catch (Exception e) {
        System.out.println("Error exiting program: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Error exiting program: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void menuItemPersegiAction() {
    try {
        PersegiView pv = new PersegiView();
        panelHome.add(pv);
        pv.setVisible(true);
    } catch (Exception error) {
        System.err.println("Error at HomeView-menuItemPersegiAction, details: " + error.toString());
        JOptionPane.showMessageDialog(this, "Error at HomeView-menuItemPersegiAction, details: " + error.toString());
    }
}

private void menuItemTabungAction() {
    try {
        TabungView tv = new TabungView();
        panelHome.add(tv);
        tv.setVisible(true);
    } catch (Exception error) {
        System.err.println("Error at HomeView-menuItemTabungAction, details: " + error.toString());
        JOptionPane.showMessageDialog(this, "Error at HomeView-menuItemTabungAction, details: " + error.toString());
    }
}

private void menuItemKubusAction() {
    try {
        KubusView kv = new KubusView();
        panelHome.add(kv);
        kv.setVisible(true);
    } catch (Exception error) {
        System.err.println("Error at HomeView-menuItemKubusAction, details: " + error.toString());
        JOptionPane.showMessageDialog(this, "Error at HomeView-menuItemKubusAction, details: " + error.toString());
    }
}

private void menuItemBalokAction() {
    try {
        BalokView bv = new BalokView();
        panelHome.add(bv);
        bv.setVisible(true);
    } catch (Exception error) {
        System.err.println("Error at HomeView-menuItemBalokAction, details: " + error.toString());
        JOptionPane.showMessageDialog(this, "Error at HomeView-menuItemBalokAction, details: " + error.toString());
    }
}



}
