/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bukutelepon;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
    DefaultTableModel tabMode;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        tabMode = (DefaultTableModel) jTable2.getModel();
        tampilkandata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextFieldKode = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNoTelepon = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        New = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        comboBoxStatus = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BUKU TELEPON");

        jLabel2.setText("Kode");

        jLabel3.setText("Nama");

        jLabel4.setText("No Telepon");

        jLabel5.setText("Email");

        jLabel6.setText("Alamat");

        jLabel7.setText("Daftar");

        jLabel8.setText("Status");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "NoTelepon", "Email", "Alamat", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        Simpan.setText("Save");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teman", "Pacar", "Keluarga" }));
        comboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNama)
                            .addComponent(jTextFieldNoTelepon)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldAlamat)
                            .addComponent(comboBoxStatus, 0, 443, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(New, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 353, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jTextFieldNoTelepon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void tampilkandata() {
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0); // Hapus semua baris yang ada

    try {
        String sql = "SELECT * FROM daftar";
        java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet rs = stm.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("Kode"),
                rs.getString("Nama"),
                rs.getString("NoTelepon"),
                rs.getString("Email"),
                rs.getString("Alamat"),
                rs.getString("Status")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}
    
    public void hapustable(){
        
        int row = tabMode.getRowCount();
        for(int i=0;i<row; i++){
            tabMode.removeRow(0);
        }
    }

    private void TampilActionPerformed(java.awt.event.ActionEvent evt) {                                         
    try {
        // Mendapatkan baris yang dipilih dari JTable
        int row = jTable2.getSelectedRow();
        String tabelKlik = jTable2.getModel().getValueAt(row, 0).toString();

        // Membuat koneksi ke database
        java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();

        // SQL untuk mendapatkan data berdasarkan Kode
        String sql = "SELECT * FROM daftar WHERE Kode = '" + tabelKlik + "'";

        // Eksekusi query
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sqlResult = stm.executeQuery(sql);

        // Menampilkan data ke form jika ditemukan
        if (sqlResult.next()) {
            String add1 = sqlResult.getString("Kode");
            jTextFieldKode.setText(add1);

            String add2 = sqlResult.getString("Nama");
            jTextFieldNama.setText(add2);

            String add3 = sqlResult.getString("NoTelepon");
            jTextFieldNoTelepon.setText(add3);

            String add4 = sqlResult.getString("Email");
            jTextFieldEmail.setText(add4);

            String add5 = sqlResult.getString("Alamat");
            jTextFieldAlamat.setText(add5);

            String add6 = sqlResult.getString("Status");
            comboBoxStatus.setSelectedItem(add6);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Kesalahan", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}


    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        jTextFieldKode.setText("");
        jTextFieldNama.setText("");
        jTextFieldNoTelepon.setText("");
        jTextFieldEmail.setText("");
        jTextFieldAlamat.setText("");
        comboBoxStatus.setSelectedIndex(0);
    }//GEN-LAST:event_NewActionPerformed

    private void comboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxStatusActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
// Ambil nilai dari form
    String kode = jTextFieldKode.getText();
    String nama = jTextFieldNama.getText();
    String noTelepon = jTextFieldNoTelepon.getText();
    String email = jTextFieldEmail.getText();
    String alamat = jTextFieldAlamat.getText();
    String status = comboBoxStatus.getSelectedItem().toString();

    // Validasi input
    if (kode.isEmpty() || nama.isEmpty() || noTelepon.isEmpty() || email.isEmpty() || alamat.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();

        // Periksa apakah data dengan kode ini sudah ada di database
        String checkSql = "SELECT * FROM daftar WHERE Kode = ?";
        java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql);
        checkStmt.setString(1, kode);
        java.sql.ResultSet rs = checkStmt.executeQuery();

        if (rs.next()) {
            // Jika data dengan kode ini sudah ada, lakukan update (EDIT)
            String updateSql = "UPDATE daftar SET Nama = ?, NoTelepon = ?, Email = ?, Alamat = ?, Status = ? WHERE Kode = ?";
            java.sql.PreparedStatement updateStmt = conn.prepareStatement(updateSql);
            updateStmt.setString(1, nama);
            updateStmt.setString(2, noTelepon);
            updateStmt.setString(3, email);
            updateStmt.setString(4, alamat);
            updateStmt.setString(5, status);
            updateStmt.setString(6, kode);

            updateStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        } else {
            // Jika data dengan kode ini belum ada, lakukan insert (SAVE)
            String insertSql = "INSERT INTO daftar (Kode, Nama, NoTelepon, Email, Alamat, Status) VALUES (?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement insertStmt = conn.prepareStatement(insertSql);
            insertStmt.setString(1, kode);
            insertStmt.setString(2, nama);
            insertStmt.setString(3, noTelepon);
            insertStmt.setString(4, email);
            insertStmt.setString(5, alamat);
            insertStmt.setString(6, status);

            insertStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data baru berhasil disimpan!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }

    // Perbarui JTable
    tampilkandata();

    // Bersihkan form
    jTextFieldKode.setText("");
    jTextFieldNama.setText("");
    jTextFieldNoTelepon.setText("");
    jTextFieldEmail.setText("");
    jTextFieldAlamat.setText("");
    comboBoxStatus.setSelectedIndex(0);

    // Aktifkan kembali "Kode" untuk input baru
    jTextFieldKode.setEditable(true);
    }//GEN-LAST:event_SimpanActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
         int selectedRow = jTable2.getSelectedRow();

    // Periksa apakah ada baris yang dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus dari tabel!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Ambil nilai "Kode" dari kolom pertama pada baris yang dipilih
    String kode = jTable2.getValueAt(selectedRow, 0).toString();

    // Konfirmasi penghapusan
    int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data dengan Kode: " + kode + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        // Hapus data dari database
        String sql = "DELETE FROM daftar WHERE Kode = ?";
        java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, kode);

        int rowsAffected = pst.executeUpdate(); // Menangkap jumlah baris yang dihapus
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan di database!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }

    // Perbarui data di JTable
    tampilkandata();
    }//GEN-LAST:event_DeleteActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
     // Periksa apakah ada baris yang dipilih di JTable
    int selectedRow = jTable2.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin diedit dari tabel!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Ambil nilai dari baris yang dipilih di JTable
    String kode = jTable2.getValueAt(selectedRow, 0).toString();
    String nama = jTable2.getValueAt(selectedRow, 1).toString();
    String noTelepon = jTable2.getValueAt(selectedRow, 2).toString();
    String email = jTable2.getValueAt(selectedRow, 3).toString();
    String alamat = jTable2.getValueAt(selectedRow, 4).toString();
    String status = jTable2.getValueAt(selectedRow, 5).toString();

    // Isi data ke form
    jTextFieldKode.setText(kode);
    jTextFieldNama.setText(nama);
    jTextFieldNoTelepon.setText(noTelepon);
    jTextFieldEmail.setText(email);
    jTextFieldAlamat.setText(alamat);
    comboBoxStatus.setSelectedItem(status);

    // Pastikan "Kode" tidak bisa diedit
    jTextFieldKode.setEditable(false);
    
    // Tampilkan pesan untuk memberi tahu pengguna bahwa data siap diedit
    JOptionPane.showMessageDialog(null, "Data telah diambil. Silakan lakukan perubahan pada form, lalu klik tombol 'Simpan' untuk memperbarui data.");

    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton New;
    private javax.swing.JButton Simpan;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldKode;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNoTelepon;
    // End of variables declaration//GEN-END:variables
}
